stages:
  - build
  - test
  - sastscan

# Étape build
build:
  stage: build
  image: maven:3.8.5-openjdk-17-slim
  script:
    - mvn clean package
  tags:
    - docker

# Étape test
test:
  stage: test
  image: maven:3.8.5-openjdk-17-slim
  script:
    - mvn clean test
  tags:
    - docker

# Étape SAST (analyse SonarCloud)
sastscan:
  stage: sastscan
  image: maven:3.8.5-openjdk-17-slim
  script:
    - curl -sSLo sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
    - unzip sonar-scanner.zip
    - ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
        -Dsonar.projectKey=8f51e9d87c71fd38871a7c0267bb4b10acd24b5b \
        -Dsonar.organization=rubenribeiro91 \
        -Dsonar.host.url=https://sonarcloud.io/ \
        -Dsonar.login=14ad4818f21384add02744d3f9e34d
  tags:
    - docker
